// web-platform/components/google-signin-button.tsx
"use client";

import { useEffect, useRef, useState } from "react";
import Script from "next/script";
import { useRouter } from "next/navigation";
import { useAuth } from "@/providers/auth-provider";
import { getErrorMessage } from "@/lib/utils";
import { toast } from "sonner";

// Minimal subset of the Google Identity Services API we use.
type GoogleCredentialResponse = { credential: string };

type GoogleAccountsId = {
  initialize(config: {
    client_id: string;
    callback: (response: GoogleCredentialResponse) => void;
  }): void;
  renderButton(
    parent: HTMLElement,
    options: {
      type?: "standard" | "icon";
      theme?: "outline" | "filled_blue" | "filled_black";
      size?: "small" | "medium" | "large";
      text?: "signin_with" | "signup_with" | "continue_with" | "signin";
      shape?: "rectangular" | "pill" | "circle" | "square";
      width?: number;
    },
  ): void;
};

declare global {
  interface Window {
    google?: {
      accounts?: { id?: GoogleAccountsId };
    };
  }
}

export function GoogleSignInButton({ next }: { next?: string }) {
  const clientId = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;
  const router = useRouter();
  const { loginWithGoogle } = useAuth();
  const buttonRef = useRef<HTMLDivElement>(null);
  const renderedRef = useRef(false);
  const [scriptReady, setScriptReady] = useState(false);

  // Render the Google-supplied button once both the script and our DOM target exist.
  // The renderedRef guard keeps this idempotent without a state-write inside the effect.
  useEffect(() => {
    if (!scriptReady || renderedRef.current || !clientId || !buttonRef.current) return;
    const gsi = window.google?.accounts?.id;
    if (!gsi) return;

    gsi.initialize({
      client_id: clientId,
      callback: async (response) => {
        try {
          await loginWithGoogle(response.credential);
          router.push(next ?? "/");
        } catch (err) {
          toast.error(getErrorMessage(err, "Google sign-in failed"));
        }
      },
    });

    gsi.renderButton(buttonRef.current, {
      type: "standard",
      theme: "outline",
      size: "large",
      text: "continue_with",
      shape: "pill",
      width: 320,
    });
    renderedRef.current = true;
  }, [scriptReady, clientId, loginWithGoogle, router, next]);

  if (!clientId) return null;

  return (
    <>
      <Script
        src="https://accounts.google.com/gsi/client"
        strategy="afterInteractive"
        onReady={() => setScriptReady(true)}
      />
      <div ref={buttonRef} className="flex justify-center" />
    </>
  );
}

// vue-platform/src/components/GoogleSignInButton.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useAuthStore } from '@/stores/auth';
import { useRouter } from 'vue-router';

const props = defineProps<{
  next?: string;
}>();

const authStore = useAuthStore();
const router = useRouter();
const buttonRef = ref<HTMLDivElement | null>(null);

const clientId = import.meta.env.VITE_GOOGLE_CLIENT_ID;

type GoogleCredentialResponse = { credential: string };

type GoogleAccountsId = {
  initialize(config: {
    client_id: string;
    callback: (response: GoogleCredentialResponse) => void;
  }): void;
  renderButton(
    parent: HTMLElement,
    options: {
      type?: 'standard' | 'icon';
      theme?: 'outline' | 'filled_blue' | 'filled_black';
      size?: 'small' | 'medium' | 'large';
      text?: 'signin_with' | 'signup_with' | 'continue_with' | 'signin';
      shape?: 'rectangular' | 'pill' | 'circle' | 'square';
      width?: number;
    }
  ): void;
};

declare global {
  interface Window {
    google?: {
      accounts?: { id?: GoogleAccountsId };
    };
  }
}

const handleCredentialResponse = async (response: GoogleCredentialResponse) => {
  if (!response.credential) return;
  const success = await authStore.loginWithGoogle(response.credential);
  if (success) {
    router.push(props.next || '/');
  }
};

const initGoogleSignIn = () => {
  if (!clientId || !buttonRef.value) return;

  const gsi = window.google?.accounts?.id;
  if (gsi) {
    gsi.initialize({
      client_id: clientId,
      callback: handleCredentialResponse,
    });

    gsi.renderButton(buttonRef.value, {
      type: 'standard',
      theme: 'outline',
      size: 'large',
      text: 'continue_with',
      shape: 'pill',
      width: 320,
    });
  }
};

onMounted(() => {
  if (!clientId) return;

  if (window.google?.accounts?.id) {
    initGoogleSignIn();
  } else {
    // Load script dynamically if not present
    const existingScript = document.getElementById('google-gsi-script');
    if (!existingScript) {
      const script = document.createElement('script');
      script.id = 'google-gsi-script';
      script.src = 'https://accounts.google.com/gsi/client';
      script.async = true;
      script.defer = true;
      script.onload = () => {
        initGoogleSignIn();
      };
      document.head.appendChild(script);
    } else {
      existingScript.addEventListener('load', initGoogleSignIn);
    }
  }
});
</script>

<template>
  <div v-if="clientId" class="google-auth-container">
    <div class="divider">
      <span>OR</span>
    </div>
    <div ref="buttonRef" class="google-btn-wrapper"></div>
  </div>
</template>

<style scoped>
.google-auth-container {
  width: 100%;
  margin-top: 20px;
  display: flex;
  flex-direction: column;
  align-items: center;
}

.divider {
  width: 100%;
  display: flex;
  align-items: center;
  text-align: center;
  margin-bottom: 20px;
  color: var(--text-muted);
  font-size: 0.75rem;
  letter-spacing: 1px;
}

.divider::before,
.divider::after {
  content: '';
  flex: 1;
  border-bottom: 1px solid var(--border-subtle);
}

.divider span {
  padding: 0 12px;
}

.google-btn-wrapper {
  display: flex;
  justify-content: center;
  width: 100%;
}
</style>
